[package]
name = "anna"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
ordered-float = "3.7.0"
rand = "0.8.5"
roaring = "0.10.1"
serde = "1.0.164"
